### ISSUE TITLE
How do I trigger in linux?

### ISSUE THREAD

**Issue by kjjuno** [jonsmithers/vscode-open-in-vim#1]
I'm trying everything I can to trigger this, but I'm not on a mac. I'm in linux with a standard us keyboard.

What is the equivalent for cmd+shift+P?

**Comment by jonsmithers** [comment]
[ctrl+shift+P](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) should work for linux. 

I probably ought to put that in the readme instead of just the macos binding.
