### ISSUE TITLE
Open in Vim 0.4.3 reported as Malicious

### ISSUE THREAD

**Issue by ardeidae** [jonsmithers/vscode-open-in-vim#3]
Hello,

Today, I wanted to open my current edited file in Vim, but the command palette didn't show Open in Vim line. Extension is reported as malicious. I can not install or remove the plugin. Is there a workaround?

Best regards,
Matthieu

**Comment by jonsmithers** [comment]
This is a result of the [malicious `event-stream` package](https://github.com/dominictarr/event-stream/issues/116) which is a dependency of certain versions of the [`vscode` package](https://www.npmjs.com/package/vscode). I've already updated this plugin to get rid of the malicious dependency. It looks like some people at Microsoft are validating plugin updates one by one. I'm currently waiting on an email status update. Hopefully it gets validated soon!

**Comment by jonsmithers** [comment]
Block was lifted :tada:
